version: '3.5'

services:

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - www_volume:/var/www/html:ro
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: registry.gitlab.com/laemmi-dockerimages/php-fpm:7.4
    user: www-data:www-data
    volumes:
      - www_volume:/var/www/html:cached
      - ~/.ssh:/root/.ssh

volumes:
  www_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/
